sudo: required
services:
- docker
script:
- make build
deploy:
- provider: script
  script: make push
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: DOCKER_PASSWORD="$DOCKER_HUB_PASSWORD" DOCKER_USERNAME=nvogel DOCKER_REGISTRY=registry.hub.docker.com NS=nvogel make push
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: dhgDUVhwEHXeiAnGaqeFlJI+zm31G4GM7k9kbL2nEct0Lc7w5+iKS9p8vWiqSx1/jCVSby2vE+Eshtjp8f47wrnKnek05Szr/GpCGbVsnWGwxDmDJHnW0sglgTgwKpbtCuQkzC+m0tPXLqxvydH3XNPw9X9SAuvevlQfY7P01sACq2VqmdWF0VRavpNP6Qr5aNHcvf/aF741RnCSdN68qUQ2aWu8KHuFACsEgQX31aTFtOiy2kKu7+a66KCl8tjEXba23rAg8EpFGDh5ml8wgNuLkgGR/Lp/Brh0jl2kG2xKXaH0R9r8mjKQvK0pTHvZJK2rCyLMJiVsXfSeJl4qfUFR0e8U6UQkPAh0LwKMLOBbM4VwK+72StAUj4nVyHRTsfEcpj29qmTF4JXEItyQKL9qA80G3DtjC3hAceu5FqLpMnH/WHarpZlXj8MkKSUqYYb/Xw6qFkh4pPmHbwWZ+vVCbTK6mLm/9GHw19phMHpDfk5lqcKBNoA1qo8kUUCBhgMchlYo1jUnXYg8dM5mrlEvwEdCgTt6iAzHcX/7mjd75/0kDxIE6rfLENHs7cJo/JTeMeeRWRfWoArq/Qu6oxnX0MHKn10cdDGEFyxDdatbSfVJUYvznICrCiSImltQREzmmfIPQTVYi9XDazktjLmfOw47rM7BKbts6qjHurI=
  - secure: Sl5F08xp4kjbBVdv96FRusdK7yshs+d2XRDHBFoFTsj12DHLIDt52CqhmE1Cu/2SvC8luXNDV1jECq8WKEyChu37lCyHLjHxfMrg5JSdJwzSKDq9+HWrGHt0Ll9eomDbda19OAxE2RkyPEVwSDDdohob1cPmUkXlboNTQ+Yr44a48/kIMg/qYEfLa1FE1KzzrvOGv+j7UK3wlkaxIsAs6dbmhYTzRfn/AUT6neV4L6sXqzY+SqDahPld55DWIvdCW0pm+s5vr5KBQYmY9/y5903vJ361sYc0czPol345W1tjJGWL0FqJrYggnsN8HpOxg1MMTjFiZd3T5/EDHg2DnTk5n/6FOSKOQSrqhf7S7DuAFBc9q6R+/K4mlzyKihUw6f/qlJtC9pLE/kSvHlaqmkChDbBO4xvi2aT8ZtUqtJPtJMGGR5eg9yCQLVWuVQodrtXrIV/mFlt+9Vo7ZnmJqEp7oOD2qwHbcSnC5MwRn1b+VSp0faEUbdstklfth70x9efTMfE/s9cMR900K+DMeSqHzBBoMKaBNCyyMMuweVRfFFMc+PnqqwMicg185aIBTLZOBM2/MvOC0ExtTwriojk7+z3Bk4MHGiJKrSonMxwx2+/HXWxJuqJ0LRbY0ek+nWVTHzt/07wEb66whlQG7Z/nLTaC+6R+WF+oUOS5ydM=
