sudo: required
services:
- docker
script:
- make build
deploy:
- provider: script
  script: make push
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: DOCKER_PASSWORD="$DOCKER_HUB_PASSWORD" DOCKER_USERNAME=nvogel DOCKER_REGISTRY=registry.hub.docker.com NS=nvogel make push
  skip_cleanup: true
  on:
    tags: true
env:
  global:
# Dockerhub
  - secure: oLM4dXSiPYQ5fkAJDgQ/yweq0GhifSO4KCsII2dsNzEp76IDVY0myH/Z4qrGtoqP/BTs4USTw0ps1XE8RzMRcjyl7iTo6VT8GxG62PdI9lxpPcRY4bIAZ3Wd0vhJi87WlHB5wnO3K3uM2QQIqQpONZTDRXtP5ciEr+mTqSFiOxTUUDfYtlPpVjzUgRDMG0KFJETOS5/783izooKBwS/la9JxIyeGx5lKpfWArMHbP+yc2hvl6P8mCIn3BcZCiVdX5Ka6Wc62AS9RCBY0ZysZ0Jgindvui/8gQiXXGOXoMwTDPDWhD49xe0KTfXphA1h6bVWVzCJW3YUmBaYK5Td8pB9l1oDvu4Z6fKM2NB9wRsnY472+SU55tl/IX1Jm9X/Cpc1HUvGHD448/0/JJbJYYcHohDbYyOq/MC+xReIY36226Hc5HWXGbPIjrhYOit42+drl8IiWMsW+jefaM6sDNcb/5KO3h2HALOt5vJ2F9yRhFsRGk2LndWz+y0vxu4kysK3nRCH2nTWTlQrKdA+fxYMCdhK8XPMPOw1rbzM935B0uTwMXhZWgbMutgTQVXzboNTZL+U8bKRPfZf0EtyX6ttHvVm577QoD2S6WZhXAINTWoKIGZx0/q/Fp3kLUKm+DvB5b9Vkzm3W01Ch3iUpiAK0S/6yTS28uhz9AmiFsuM=
# Quay
  - secure: cg5DJARLsWmVHJw9M3FKHL6Jbsdst9uX/n8sLW1aCPT2H6HH1eySVDC8bj6U+ToATSJjOG0pGwjTG2Rmk4vabIHOLa0ZDgUD2tbvpUPjtLLZ0aG4ub8kyh2QYI/59TuH7MI4w4w1K3/+Wjw0EDZT9KS8yr9ctOjZi9zJ3EZiJ9JPY2/DEEoy1rtBY1qQENGv8OKwbKUOZBKt5nO5lAXzbsjfGSZoCScgCNPHfPjwHyX/18vDyHfVfQwkDGRoVNDe3/jWpen7TxOO0ST9x53b6v9jwz0SgdnGI5fXBatH8fZ5sHbJeesFKbm/AlMH57voBsxlt7V6eFW/hYLba9vVxY2FJpeaYYkdMxls5VlKHX3Wz2Ma/kSxrM49MOTqd1xyvrk6IEaOVNzuZiLRZGPHIVMSlll9xZNoOeV2qcv28bEZxaqM+MURfJjlExftDPAoSBfvW5PVsJBT3FojsmYm+CZ+KaKNeivJCNlZWRDlmV4eZib3ZRamiM1qLVT+eAM/kb2S0yQlh+mPTBsui+XGG8aUx2XRx1MbHy3gj7qbiad+Omp8nvj/CzqVY2t03lgOSyIx4HgtWuR6XSxfljW143OgRhPpepVjQcsl4e3mvmUsFeKTX1SP44JdSIFYE4pvSnmNPjIkT/E+2hJkXdHs7QwX6zMJ53pDCpKQwz2ybLY=
